apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-registration
  labels:
    app: user-registration
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-registration
  template:
    metadata:
      labels:
        app: user-registration
    spec:
      containers:
        - name: user-registration
          image: marlonmilesmg/user-registration:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: user-registration
spec:
  selector:
    app: user-registration
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
